### ISSUE TITLE
The parameter S3CMD_SOURCE_DIR doesn't work if it's a file name

### ISSUE THREAD

**Issue by kayelvo** [ThiagoAnunciacao/s3cmd-sync-action#7]
A forward slash incorrectly gets added to the file name, throwing this error:
`ERROR: Parameter problem: Invalid source: './parent-folder/file-name.txt/' is not an existing file or directory
`

Reference:
https://github.com/ThiagoAnunciacao/s3cmd-sync-action/blob/0ef39cfae2b5a1050883e7d29b3f3a85c7003df7/entrypoint.sh#L72

**Comment by ThiagoAnunciacao** [comment]
@kayelvo thank you for your message, I'm just submitting a new version 0.2.6 without the slash at the end of FILES_SOURCE_DIR

**Comment by kayelvo** [comment]
fantastic! thanks for the quick fix.
